Feature/pdn 3481 connect source and target database and get source schema
mmailaender/Vback pull request #2
Opened 2023-10-18 06:00 UTC by MananSoniDechea

2023-10-23 11:31 UTC, mmailaender requested changes

2023-10-23 11:31 UTC, mmailaender commented on vback/src/lib/features/database/databaseKeyInputs/model/handleOnSourceKeyChange.ts
> +	getDatabaseByKey(newKey);
you call `getDatabaseByKey`, but what is happening then there?

2023-10-25 09:13 UTC, MananSoniDechea commented on vback/src/lib/widgets/database/DatabaseInputs/ui/DatabaseInputs/DatabaseInputs.svelte
> +<div class="flex flex-col gap-[72px] p-10 max-w-[480px]">
Arbitrary value is used only in these 2 places, as there is no predefined token for gap 72 px  or for max width 480 px

2023-10-25 09:44 UTC, mmailaender commented on vback/src/lib/features/database/databaseKeyInputs/ui/DatabaseKeyInputs.svelte
> +		<div class="min-w-[80px] text-base font-regular">Source:</div>
Typo: "Target:"

2023-10-25 11:43 UTC, mmailaender submitted a review, later dismissed

2023-10-25 11:43 UTC, mmailaender commented on vback/src/lib/entities/database/api/getDatabase.ts
Based on my learnings from this blog post I also shared with you https://dmitripavlutin.com/coding-like-shakespeare-practical-function-naming-conventions/
we should replace `get` with `fetch` because it's an API call

2023-10-25 11:43 UTC, mmailaender commented on vback/src/lib/entities/database/api/getDatabase.ts
> +const getSchema = async (
fetchDatabaseSchema

2023-10-25 11:43 UTC, mmailaender commented on vback/src/lib/shared/api/getPaginated.ts
replace get with fetch see other comment

2023-10-26 04:51 UTC, MananSoniDechea commented on vback/src/lib/features/database/migrationKeysInput/model/handleSourceKeyChange.ts
> +	fetchDatabase(newKey);
The result is being updated in the store asynchronously

2023-10-26 06:46 UTC, mmailaender commented on vback/src/lib/features/database/migrationKeysInput/model/handleSourceKeyChange.ts
> +	const { client, fql } = fetchFaunaClient(key);
Next time, I suggest you answer my previous question instead of making a change directly because now you have introduced an inconvenient/verbose statement. 😉 A function that has nothing to do with API call is now dealing with the API client (Think also about the `Single responsible principle`.

2023-10-26 06:52 UTC, mmailaender commented on vback/src/lib/entities/database/api/fetchDatabase.ts
> +const fetchDatabaseData = async (
> Avoid the same name covering multiple concepts
> The function name indicates a well-determined type of action. It should be a one-to-one relation.

> If the same name represents many equivalent still different actions, it might be covering too many concepts and decreases readability. One-to-many — one name that covers many actions should be avoided.

> For example an application has in different classes a method named get(). Having the same name, these methods do different things: fetches data from server httpService.get(), gets the wrapped object wrapper.get() or initialize and get a storage instance Storage.get().

> These concepts are different, and should have their own distinguishable names. Correspondingly httpService.fetch(), wrapper.getWrappedValue() and Storage.initialize() function names are better.

https://dmitripavlutin.com/coding-like-shakespeare-practical-function-naming-conventions/

2023-10-26 08:31 UTC, MananSoniDechea commented on vback/src/lib/features/database/migrationKeysInput/model/handleSourceKeyChange.ts
> +	const { client, fql } = fetchFaunaClient(key);
The client is not being initialized for every api call, it is being initialized when key changes and is being passed to the api functions which utilizes it

2023-11-01 08:49 UTC, merged